services:
  # 1) Postgres database
  postgres:
    image: postgres:15-alpine
    container_name: portfolio_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stingerSTUNG618
      POSTGRES_DB: portfolio_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portfolio_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2) Your API server—runs migrations then starts
  backend:
    build: ./backend
    container_name: portfolio_backend
    restart: "no" # Change to 'no' for debugging so it doesn't restart endlessly
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    # TEMPORARY COMMAND FOR DEBUGGING MIGRATIONS
    command: >
      sh -c "echo 'Attempting Prisma migrations...' &&
             npx prisma generate --schema=prisma/schema.prisma &&
             npx prisma migrate deploy --schema=prisma/schema.prisma"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"

volumes:
  postgres_data:
